---
title: "Variables"
output: html_notebook
editor_options: 
  chunk_output_type: console
---


### Define variables used in this package
This will need to be run every time I makes changes to the package or the dataset.
```{r }
devtools::load_all()

POP <- readRDS("inst/extdata/pop_by_province_20230213.rds")
DATA <- readRDS("inst/extdata/covid_overall_20230122.rds")
cases_before <-
    DATA$cumul_symptomatic[1] + DATA$cumul_deaths[1] - DATA$symptomatic[1]
deaths_before <-
    DATA$cumul_deaths[1] - DATA$deaths[1]

PARAMETERS <- initialize_params()

CASES_OBSERVED <- c(cases_before, DATA$symptomatic[1:PARAMETERS$obslength])
DEATHS_OBSERVED <- c(deaths_before, DATA$deaths[1:PARAMETERS$obslength])
# NA's are infact zeroes
DEATHS_OBSERVED[is.na(DEATHS_OBSERVED)] = 0

usethis::use_data(POP, overwrite=TRUE)
usethis::use_data(DATA, overwrite=TRUE)
usethis::use_data(PARAMETERS, overwrite=TRUE)
usethis::use_data(CASES_OBSERVED, overwrite=TRUE)
usethis::use_data(DEATHS_OBSERVED, overwrite=TRUE)

```

### Natural history of infection
```{r}

# 1. Takahashi, K. et al. Duration of Infectious Virus Shedding by SARS-CoV-2 Omicron Variant–Infected Vaccinees. Emerging Infectious Disease journal 28, 998 (2022).
# p.999 Infectious virus was detected up to 9 days after diagnosis; the highest proportion of virus isolates (41.7%) was found in samples collected 2–5 days after diagnosis 
dur = 3.5 # 2-5 days
r = -log(0.417)/dur
1 - pexp(1, rate=0.01)

# Keske, Ş. et al. Duration of infectious shedding of SARS-CoV-2 Omicron variant and its relation with symptoms. Clin Microbiol Infect 29, 221–224 (2023).
# The PCR positivity rate on days 5, 7, 10, and 14 was 96.4% (53/55), 87.3% (48/55), 74.545% (41/55), and 41.8% (23/55) consecutively, whereas the viral culture positivity rates were 83% (44/53), 52% (26/50), 13.5% (7/52), and 8% (4/50).

# Wu, Y. et al. Incubation Period of COVID-19 Caused by Unique SARS-CoV-2 Strains: A Systematic Review and Meta-analysis. JAMA Network Open 5, e2228008–e2228008 (2022).
# incubation period is 3.42 days for the Omicron 

# Yu, W. et al. Proportion of asymptomatic infection and nonsevere disease caused by SARS-CoV-2 Omicron variant: A systematic review and analysis. Journal of Medical Virology 94, 5790–5801 (2022).
# pooled proportion of asymptomatic infection was 25.5% (95% CI 17.0–38.2) 

# Jiang, X. et al. [Latent period and incubation period with associated factors of COVID-19 caused by Omicron variant]. Zhonghua Yu Fang Yi Xue Za Zhi 57, 1–8 (2023).
# The mean latent period of 467 Omicron infections was 2.65 (95%CI: 2.53-2.78) days, and 98% of infections were positive for nucleic acid detection within 6.37 (95%CI: 5.86-6.82) days after infection. The mean incubation period of 335 symptomatic infections was 3.40 (95%CI: 3.25-3.57) days, and 97% of them developed clinical symptoms within 6.80 (95%CI: 6.34-7.22) days after infection. 


```



#### Data preparation
Prepare data for the region - population and initially infected
In particular, 함북 = 함북 + 나선, 황북 = 황북 + 개성 as we don't have the population size for 나선 and 개성.
This is used for hierarchical modeling
```{r}
# library(COVID19NorthKorea)
library(nimble) # this should come before load_all() because one of the package files uses nimbleFunction
devtools::load_all()
dlist <- rio::import_list("inst/extdata/(2022-0811)_코로나19_조선중앙TV_보도_현황표_시도별_일일유열자.xlsx")
nm <- names(dlist)[2:length(dlist)]
caselist <- vector("list", length(nm))

for (i in 1:length(nm)) {
  df <- dlist[[i+1]]
  # add a few columns to easier management and plotting
  df$case <- df$`당일 발생자수`
  df$date <- extract_dates(df$기준시)
  df$province <- nm[i]
  # df <- dplyr::full_join(fulldate_df, df, by="date")
  caselist[[i]] <- df
}

mindate <- min(do.call("c", (lapply(caselist, function(x) min(x$date)))))
maxdate <- max(do.call("c", (lapply(caselist, function(x) max(x$date)))))

fulldate_df <- data.frame(date = seq(mindate, maxdate, by="day"))

for (i in 1:length(nm)) {
  df <- caselist[[i]]
  fulldate_df$province <- df$province[1]
  df <- dplyr::full_join(fulldate_df, df, by="date")
  df <- dplyr::rename(df, province = province.x)
  caselist[[i]] <- df
}

dat <- do.call("rbind", caselist)
dat <- dat[, !names(dat) %in% c("province.y")]


# population data based on 2008 census
pop <- readxl::read_xlsx("inst/extdata/census_2008.xlsx")
unique(df$province)
pop <- dplyr::rename(pop, province_English = Province)
pop$province <- c("양강","함북","함남","강원","자강","평북","평남",
                  "황북","황남","평양","남포")

# pop <- readRDS("inst/extdata/pop_by_province_20230213.rds")
# dat <- readRDS("inst/extdata/covid_by_province_20230213.rds")
prov = unique(dat$province)
# merge cases into 함북 = 함북 + 나선, 황북 = 황북 + 개성
d <- dat[dat$province %in% c("함북","나선","황북","개성"),]
dat0 <- dat[!dat$province %in% c("함북","나선","황북","개성"),]

d1 <- d[d$province == "함북",]
d2 <- d[d$province == "나선",] 
d12 <- dplyr::full_join(d1, d2, by="date")
library(tidyr)
d12$기준시 <- d12$기준시.x
d12$보도일 <- d12$보도일.x
# update the number of cases for 함북
d12$`치료중 환자수` <- d12$`치료중 환자수.x` + d12$`치료중 환자수.y`
d12$`당일 발생자수` <- d12$`당일 발생자수.x` + d12$`당일 발생자수.y`
d12$`당일 완쾌자수` <- d12$`당일 완쾌자수.x` + d12$`당일 완쾌자수.y`
d12$`당일 사망자 수` <- d12$`당일 사망자 수.x` + d12$`당일 사망자 수.y`
d12$case <- d12$case.x + d12$case.y

# d12$symptomatic <- d12$symptomatic.x + d12$symptomatic.y
d12$province <- "함북"
d12_slim <- d12[,names(d1)]

d3 <- d[d$province == "황북",]
d4 <- d[d$province == "개성",] 
d34 <- dplyr::full_join(d3, d4, by="date")
library(tidyr)
d34$기준시 <- d34$기준시.x
d34$보도일 <- d34$보도일.x
# update the number of cases for 황북
d34$`치료중 환자수` <- d34$`치료중 환자수.x` + d34$`치료중 환자수.y`
d34$`당일 발생자수` <- d34$`당일 발생자수.x` + d34$`당일 발생자수.y`
d34$`당일 완쾌자수` <- d34$`당일 완쾌자수.x` + d34$`당일 완쾌자수.y`
d34$`당일 사망자 수` <- d34$`당일 사망자 수.x` + d34$`당일 사망자 수.y`
d34$case <- d34$case.x + d34$case.y
d34$province <- "황북"
d34_slim <- d34[, names(d1)]

datnew <- rbind(rbind(dat0, d12_slim), d34_slim)
prov <- unique(datnew$province)
sum(is.na(datnew$date))
sum(is.na(datnew$province))
# for (i in 1:length(prov)) {
#   print(nrow(datnew[datnew$province == prov[i],]))
# } 

y <- matrix(NA, nrow=nrow(d1), ncol=length(prov))
for (i in 1:length(prov)) {
  y[,i] <- datnew[datnew$province == prov[i],]$case
}
library(dplyr)

df <- data.frame(matrix(NA, nrow=length(unique(datnew$province)), 
                             ncol=3))
names(df) <- c("province", "pop", "inf0")
df$province <- prov
for (i in 1:nrow(df)) {
  df$pop[i] <- pop[pop$province == df$province[i],]$Total
  d <- datnew[datnew$province == df$province[i], ]
  df$inf0[i] <- d$`치료중 환자수`[1] + d$`당일 완쾌자수`[1] + d$`당일 사망자 수`[1] - d$`당일 발생자수`[1]
}
# y time-series data
# df population size, initially infected, prove
# ----------------------------------------------------------
nkcovid = vector('list', 3)
nkcovid[[1]] = datnew
nkcovid[[2]] = y
nkcovid[[3]] = df
names(nkcovid) = c("covid", "incidence", "pop")
usethis::use_data(nkcovid, overwrite=TRUE)
```


