---
title: "Descriptive_statistics_CK"
author: "Jong-Hoon Kim, Chaelin Kim"
output: html_document

# modified descriptive statistics
---

```{r}
library(COVID19NorthKorea)
dlist <- rio::import_list("inst/extdata/(2022-0811)_코로나19_조선중앙TV_보도_현황표_시도별_일일유열자.xlsx")
nm <- names(dlist)[2:length(dlist)]
caselist <- vector("list", length(nm))

for (i in 1:length(nm)) {
  # df <- data.frame(case = dlist[[i+1]]$`당일 발생자수`)
  df <- dlist[[i+1]]
  # add a few columns to easier management and plotting
  df$case <- dlist[[i+1]]$`당일 발생자수`
  df$date <- extract_dates(dlist[[i+1]]$기준시)
  df$province <- nm[i]
  caselist[[i]] <- df
}

df <- do.call("rbind", caselist)

# 시도명 (Province) | 초기 날짜 (Initial Date) | 최종 날짜 (Final Date) | 기간 (Duration) | 일일 최대 발생자 날짜 (Date of the Highest Daily New Cases) | 일일 최대 발생자 수 (Maximum Daily New Cases) | 누적 발생자 수 (Cumulative Cases) | 누적 완쾌자 수 (Cumulative Recovered Cases) | 누적 사망자 수 (Cumulative Death Cases) | 인구 수 (Population) | 발병률 (Incidence Rate)

# create a summary table
library(dplyr)
library(lubridate)

df <- subset(df, !is.na(case))

# summary table -- regional estimates
df_ds <- df %>%
  group_by(province) %>%
  summarize(
    initial_date         = min(date[case != 0]),
    final_date           = max(date[case != 0]),
    duration             = as.numeric(difftime(final_date, initial_date, units="days")) + 1,
    max_daily_cases_date = date[which.max(case)],
    max_daily_cases      = max(case),
    adding_new_cases     = sum(case),
    cumulative_recovered = sum(`당일 완쾌자수`, na.rm=T),
    cumulative_deaths    = sum(`당일 사망자 수`, na.rm=T),
    cumulative_cases     = cumulative_recovered + cumulative_deaths)

pop = POP[,c("Total", "Province_Korean", "Province")]
pop$Province[pop$Province == "Kangwon"] <- "Gangwon"

df_ds$Province_Korean = df_ds$province
df_ds = left_join(df_ds, pop, by="Province_Korean")

# Nasun City merged with Hamgyeongbuk Province, and Kaesong merged with Hwanghaebuk Province.
# 개성 = 황해북도 https://namu.wiki/w/%EA%B0%9C%EC%84%B1%EC%8B%9C
# 나선 = 함경북도 https://namu.wiki/w/%EB%9D%BC%EC%84%A0%EC%8B%9C?from=%EB%82%98%EC%84%A0%EC%8B%9C

df_ds[df_ds$province == "황북","adding_new_cases"] = df_ds[df_ds$province == "황북","adding_new_cases"] +  df_ds[df_ds$province == "개성","adding_new_cases"] 
df_ds[df_ds$province == "함북","adding_new_cases"] = df_ds[df_ds$province == "함북","adding_new_cases"] +  df_ds[df_ds$province == "나선","adding_new_cases"]

df_ds[df_ds$province == "황북","cumulative_recovered"] = df_ds[df_ds$province == "황북","cumulative_recovered"] +  df_ds[df_ds$province == "개성","cumulative_recovered"] 
df_ds[df_ds$province == "함북","cumulative_recovered"] = df_ds[df_ds$province == "함북","cumulative_recovered"] +  df_ds[df_ds$province == "나선","cumulative_recovered"]

df_ds[df_ds$province == "황북","cumulative_deaths"] = df_ds[df_ds$province == "황북","cumulative_deaths"] +  df_ds[df_ds$province == "개성","cumulative_deaths"] 
df_ds[df_ds$province == "함북","cumulative_deaths"] = df_ds[df_ds$province == "함북","cumulative_deaths"] +  df_ds[df_ds$province == "나선","cumulative_deaths"]

df_ds[df_ds$province == "황북","cumulative_cases"] = df_ds[df_ds$province == "황북","cumulative_cases"] +  df_ds[df_ds$province == "개성","cumulative_cases"] 
df_ds[df_ds$province == "함북","cumulative_cases"] = df_ds[df_ds$province == "함북","cumulative_cases"] +  df_ds[df_ds$province == "나선","cumulative_cases"]

# estimate attack rate
df_ds$attack_rate = round(100 * df_ds$cumulative_cases / df_ds$Total, digits = 1)
df_ds <- df_ds[order(df_ds$Province),]

# edit formatting
summary_table <- df_ds
summary_table <- summary_table[!summary_table$province %in% c("개성", "나선"), ]
summary_table$attack_rate_percent   <- paste0(summary_table$attack_rate,"%")
summary_table$max_daily_cases       <- sapply(summary_table$max_daily_cases, format, big.mark = ",")
summary_table$adding_new_cases      <- sapply(summary_table$adding_new_cases, format, big.mark = ",")
summary_table$cumulative_recovered  <- sapply(summary_table$cumulative_recovered, format, big.mark = ",")
summary_table$cumulative_deaths     <- sapply(summary_table$cumulative_deaths, format, big.mark = ",")
summary_table$cumulative_cases      <- sapply(summary_table$cumulative_cases, format, big.mark = ",")
summary_table$Total                 <- sapply(summary_table$Total, format, big.mark = ",")

summary_table_en <- summary_table[, c("Province", "initial_date", "final_date", 
                           "duration", "max_daily_cases_date", "max_daily_cases", 
                           "cumulative_cases", "cumulative_recovered", "cumulative_deaths" , 
                           "Total", "attack_rate_percent")]

write.csv(summary_table_en, file = "outputs/summary_table_en.csv", row.names = FALSE)

summary_table_kr <- summary_table[, c("province", "initial_date", "final_date", 
                           "duration", "max_daily_cases_date", "max_daily_cases", 
                           "cumulative_cases", "cumulative_recovered", "cumulative_deaths" , 
                           "Total", "attack_rate_percent")]

summary_table_kr <- summary_table_kr[order(summary_table_kr$province), ]

write.csv(summary_table_kr, file = "outputs/summary_table_kr.csv", row.names = FALSE)

# compare the cumulative cases estimates and sum of new cases
# overall estimates
df_cases_all <- df %>%
  summarize(
    Province             = "Korean Central TV Total", 
    adding_new_cases     = sum(case),
    cumulative_recovered = sum(`당일 완쾌자수`),
    cumulative_deaths    = sum(`당일 사망자 수`),
    cumulative_cases     = cumulative_recovered + cumulative_deaths)

df_cases_all$adding_new_cases     <- sapply(df_cases_all$adding_new_cases, format, big.mark = ",")
df_cases_all$cumulative_recovered <- sapply(df_cases_all$cumulative_recovered, format, big.mark = ",")
df_cases_all$cumulative_deaths    <- sapply(df_cases_all$cumulative_deaths, format, big.mark = ",")
df_cases_all$cumulative_cases     <- sapply(df_cases_all$cumulative_cases, format, big.mark = ",")

# regional estimates
df_cases_region_en <- summary_table[, c("Province",
                             "adding_new_cases", "cumulative_recovered", 
                             "cumulative_deaths", "cumulative_cases")]

df_cases_en <- rbind(df_cases_region_en, df_cases_all)

df_cases_region_kr <- summary_table[, c("province",
                             "adding_new_cases", "cumulative_recovered", 
                             "cumulative_deaths", "cumulative_cases")]

df_cases_region_kr <- df_cases_region_kr[order(df_cases_region_kr$province), ]

colnames(df_cases_region_kr)[1] <- "Province"

df_cases_kr <- rbind(df_cases_region_kr, df_cases_all)

# save csv
write.csv(df_cases_kr, file = "outputs/summary_table_total_kr.csv", row.names = FALSE)
```


```{r}
# compare 노동신문 and 조선중앙TV data by dates (기준시)

library(readxl)

summary_dates_KCTV <- df %>% group_by(date) %>%
  summarize("신규 유열자(조선중앙TV)" = sum(case),
            "완쾌자 (조선중앙TV)"     = sum(`당일 완쾌자수`),
            "사망자 (조선중앙TV)"     = sum(`당일 사망자 수`))

summary_dates_labor <- read_excel("inst/extdata/(2022-0811)_코로나19_노동신문_보도_현황표_전체_일일유열자 2.xlsx")

names(summary_dates_labor) <- c("기준일", "신규 유열자(노동신문)", "완쾌자(노동신문)", "사망자(노동신문)")

summary_dates <- left_join(summary_dates_labor, summary_dates_KCTV, by = c("기준일" = "date"))

# convert character column to numeric
summary_dates$`완쾌자(노동신문)` <- as.numeric(summary_dates$`완쾌자(노동신문)`)

summary_dates_table <- summary_dates %>%
  mutate(across(2:7, ~ format(., big.mark = ",")))

# replace "     NA" with "-" in each column
summary_dates_table <- as.data.frame(apply(summary_dates_table , 2, function(x) gsub("^\\s*NA$", "-", x)))
summary_dates_table$기준일 <- format(as.Date(summary_dates_table$기준일), "%Y/%m/%d")

# save csv
write.csv(summary_dates_table, file = "outputs/summary_dates.csv", row.names = FALSE)

```


```{r}
# regional trend -- edits based on JK's code
 library(ggplot2)
 library(scales)

 p <-ggplot(df, aes(date, case))+
   geom_col(fill="brown", alpha=0.5)+
   theme_bw() +
   labs(x="", y="유열자 수") +
   scale_y_continuous(labels = comma) + 
   theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)))

 ggsave("plots/plot_dates.png", plot = p, width = 4.5, height = 4.5, dpi = 300)
 
# 두 자료원 트렌드 한 그래프에 나타내기
  library(dplyr)

# 데이터 프레임 변환
df_long <- summary_dates %>%
   tidyr::pivot_longer(cols = c(`신규 유열자(조선중앙TV)`, `신규 유열자(노동신문)`), 
                      names_to = "source", values_to = "case")
df_long$기준일 <- as.Date(df_long$기준일, format="%Y-%m-%d")

# 그래프 생성 - English
p2_en <- ggplot(df_long, aes(x = 기준일, y = case)) +
  geom_col(data = subset(df_long, source == "신규 유열자(조선중앙TV)"), aes(fill = source), alpha = 0.5) +
  geom_line(data = subset(df_long, source == "신규 유열자(노동신문)"), aes(color = source), size = 1) +
  scale_fill_manual(values = c("brown"), labels = c("New cases (Korean Central TV)"), name = "Data Source") +
  scale_color_manual(values = c("blue"), labels = c("New cases (Rodong Sinmun)"), name = "Data Source") +
  theme_bw() +
  labs(x = "", y = "New cases") +
  scale_y_continuous(labels = scales::comma) +
  theme(
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
    legend.title = element_blank()
  )

p2_en

# ggsave("plots/plot_dates2_en.png", plot = p2_en, width = 6.5, height = 4.5, dpi = 300)


# format updated
p2_en <- ggplot(df_long, aes(x = 기준일, y = case)) +
  geom_col(data = subset(df_long, source == "신규 유열자(노동신문)"), aes(fill = source), alpha = 0.2) +
  geom_col(data = subset(df_long, source == "신규 유열자(조선중앙TV)"), aes(fill = source), alpha = 0.5) +
  scale_fill_manual(values = c("blue", "brown"), labels = c("New cases (Rodong Sinmun)", "New cases (Korean Central TV)"), name = "Data Source") +
  theme_bw() +
  labs(x = "", y = "New cases") +
  scale_y_continuous(labels = scales::comma) +
  theme(
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
    legend.title = element_blank(),
    legend.position = c(0.75, 0.85)  # Adjust the values to control the position of the legend
  )

ggsave("plots/plot_dates2_en.png", plot = p2_en, width = 6.5, height = 4.5, dpi = 300)


# format updated - Korean
p2_kr <- ggplot(df_long, aes(x = 기준일, y = case)) +
  geom_col(data = subset(df_long, source == "신규 유열자(노동신문)"), aes(fill = source), alpha = 0.2) +
  geom_col(data = subset(df_long, source == "신규 유열자(조선중앙TV)"), aes(fill = source), alpha = 0.5) +
  scale_fill_manual(values = c("blue", "brown"), labels = c("신규 유열자 (노동신문)", "신규 유열자 (조선중앙TV)"), name = "Data Source") +
  theme_bw() +
  labs(x = "", y = "유열자 수") +
  scale_y_continuous(labels = scales::comma) +
  theme(
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
    legend.title = element_blank(),
    legend.position = c(0.75, 0.85)  # Adjust the values to control the position of the legend
  )

ggsave("plots/plot_dates2_kr.png", plot = p2_kr, width = 6.5, height = 4.5, dpi = 300)

# 지역별
  f <-ggplot(df, aes(date, case))+
   geom_col(fill="brown", alpha=0.5)+
   theme_bw() +
   labs(x="", y="유열자 수") +
   facet_wrap(~province) +
   theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)))

  
 ggsave("plots/plot_dates_facet.png", plot = f, width = 3.4*2.8, height = 3.4*2.8, dpi = 1200)
 
 # regional cases graph - English
 province_name <- summary_table[, c("province", "Province")]
 cases_regional <- df
 cases_regional <- left_join(cases_regional, province_name, by = "province")
 cases_regional <- cases_regional[!cases_regional$province %in% c("개성", "나선"), ]

  f2 <- ggplot(cases_regional, aes(date, case)) +
  geom_col(fill = "brown", alpha = 0.5) +
  theme_bw() +
  labs(x = "", y = "New cases") +
  facet_wrap(~ Province, scales = "free_y") +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
        axis.text.x = element_text(angle = 45, hjust = 1))

  ggsave("plots/plot_dates_facet_en.png", plot = f2, widt=3.4*2.5, height=2.7*2.5, units="in")
  
  # regional cases graph - Korean
  f3 <- ggplot(cases_regional, aes(date, case)) +
  geom_col(fill = "brown", alpha = 0.5) +
  theme_bw() +
  labs(x = "", y = "유열자 수") +
  facet_wrap(~ province, scales = "free_y") +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
        axis.text.x = element_text(angle = 45, hjust = 1))

  ggsave("plots/plot_dates_facet_kr.png", plot = f3, widt=3.4*2.5, height=2.7*2.5, units="in")
 

```


```{r}
# 월별 신규열자 지도
library(lubridate)
library(data.table)
library(scales)
library(ggplot2)
library(RColorBrewer)

df_month <- df
df_month$month <- month.name[month(ymd(df_month$date))]

df_month <- df_month %>%
  group_by(month, province) %>%
  summarize(adding_new_cases = sum(case))
    
df_month <- data.table(df_month)

df_May  <- df_month[month == "May",]
df_June <- df_month[month == "June",]
df_July <- df_month[month == "July",]

# 지도 그리기
dprk = rgdal::readOGR("inst/extdata/gadm41_PRK_shp", "gadm41_PRK_1")
dprk@data$name_kor = c("자강","함북","함남","황북","황남","개성","강원","강원","평북","평남","평양","나선","양강","평북")

dprk@data$cases_May  = NA
dprk@data$cases_June = NA
dprk@data$cases_July = NA

nm = dprk@data$name_kor

for (n in nm){
  dprk@data[dprk@data$name_kor == n,]$cases_May = df_May[df_May$province == n,]$adding_new_cases }

for (n in nm){
  dprk@data[dprk@data$name_kor == n,]$cases_June = df_June[df_June$province == n,]$adding_new_cases }

for (n in nm){
  dprk@data[dprk@data$name_kor == n,]$cases_July = df_July[df_July$province == n,]$adding_new_cases }

# tidy the data
dprk_df_May <- broom::tidy(dprk, region = "cases_May")
dprk_df_May$id <- as.double(dprk_df_May$id) # new cases for May

dprk_df_June <- broom::tidy(dprk, region = "cases_June")
dprk_df_June$id <- as.double(dprk_df_June$id) # new cases for June

dprk_df_July <- broom::tidy(dprk, region = "cases_July")
dprk_df_July$id <- as.double(dprk_df_July$id) # new cases for July

# create the map plot for May
map_May <- ggplot(data = dprk_df_May) +
  geom_polygon(aes(x = long, y = lat, group = group, fill = id),
               color = 'black', linewidth = 0.5) +
  coord_equal() +
  theme_map() +
  theme(legend.title = element_text(size = 12),
        legend.text = element_text(size = 12))

# create the map plot for June
map_June <- ggplot(data = dprk_df_June) +
  geom_polygon(aes(x = long, y = lat, group = group, fill = id),
               color = 'black', linewidth = 0.5) +
  coord_equal() +
  theme_map() +
  theme(legend.title = element_text(size = 12),
        legend.text = element_text(size = 12))

# create the map plot for July
map_July <- ggplot(data = dprk_df_July) +
  geom_polygon(aes(x = long, y = lat, group = group, fill = id),
               color = 'black', linewidth = 0.5) +
  coord_equal() +
  theme_map() +
  theme(legend.title = element_text(size = 12),
        legend.text = element_text(size = 12))

# add province name
shp = rgdal::readOGR("inst/extdata/gadm41_PRK_shp", "gadm41_PRK_1")
shp_df <- broom::tidy(shp, region = "NAME_1")

# Create the map plot with province name
cnames <- aggregate(cbind(long, lat) ~ id, data = shp_df, FUN = mean)

library(stringr)
unique_names <- unique(cnames$id)


# English map
# define the replacements
replacements <- c("Chagang-do"     = "Jagang",
                  "Hamgyŏng-bukto" = "North Hamgyong",
                  "Hamgyŏng-namdo" = "South Hamgyong",
                  "Hwanghae-bukto" = "North Hwanghae",
                  "Hwanghae-namdo" = "South Hwanghae", 
                  "Kaesŏng"        = " ",
                  "Kangwŏn-do"     = "Gangwon",
                  "Kumgangsan"     = " ",
                  "P'yŏngan-bukto" = "North Pyongan",
                  "P'yŏngan-namdo" = "South Pyongan",
                  "P'yŏngyang"     = "Pyongyang",
                  "Rasŏn"          = " ",
                  "Ryanggang"      = "Ryanggang",
                  "Sinŭiju"        = " ")

# Modify labels in cnames data frame
cnames$id <- str_replace_all(cnames$id, replacements)

# correct label location
cnames$lat[cnames$id  == "North Pyongan"]   <- 40
cnames$long[cnames$id == "North Pyongan"]   <- 125.2
cnames$lat[cnames$id  == "South Pyongan"]   <- 39.45
cnames$long[cnames$id == "South Pyongan"]   <- 126.1
cnames$lat[cnames$id  == "South Hamgyong"]  <- 40.25
cnames$long[cnames$id == "South Hamgyong"]  <- 127.8
cnames$lat[cnames$id  == "South Hwanghae"]  <- 38.3
cnames$long[cnames$id == "South Hwanghae"]  <- 125.6

cnames$lat[cnames$id  == "Gangwon"]         <- 38.7
cnames$long[cnames$id == "Gangwon"]         <- 127.5
cnames$lat[cnames$id  == "North Hamgyong"]  <- 42
cnames$long[cnames$id == "North Hamgyong"]  <- 129.6
cnames$long[cnames$id == "Ryanggang"]       <- 128.25

# create the map with province name: cases in May
map_cases_May_en <- map_May  + 
  geom_text(data = cnames, aes(x = long, y = lat, label = id), size = 4, color = "#505050") +
  scale_fill_gradientn(colors = brewer.pal(9, "YlOrBr"),
                       limits = c(0, max(df_month$adding_new_cases)),
                       breaks = seq(0, max(df_month$adding_new_cases), 100000),
                       labels = comma,
                       "New cases (May)") +
  theme(legend.position = c(0.9, 0.25))

# save the map with the province name: cases in May
ggsave(paste0("plots/map_cases_May_en", ".png"),
       map_cases_May_en, width=7.4, height=7.4, units="in")

# create the map with province name: cases in June
map_cases_June_en <- map_June  + 
  geom_text(data = cnames, aes(x = long, y = lat, label = id), size = 4, color = "#505050") +
  scale_fill_gradientn(colors = brewer.pal(9, "YlOrBr"),
                       limits = c(0, max(df_month$adding_new_cases)),
                       breaks = seq(0, max(df_month$adding_new_cases), 100000),
                       labels = comma,
                       "New cases (June)") +
  theme(legend.position = c(0.9, 0.25))

# save the map with the province name: cases in June
ggsave(paste0("plots/map_cases_June_en", ".png"),
       map_cases_June_en, width=7.4, height=7.4, units="in")

# create the map with province name: cases in July
map_cases_July_en <- map_July  + 
  geom_text(data = cnames, aes(x = long, y = lat, label = id), size = 4, color = "#505050") +
  scale_fill_gradientn(colors = brewer.pal(9, "YlOrBr"),
                       limits = c(0, max(df_month$adding_new_cases)),
                       breaks = seq(0, max(df_month$adding_new_cases), 100000),
                       labels = comma,
                       "New cases (July)") +
  theme(legend.position = c(0.9, 0.25))

# save the map with the province name: cases in July
ggsave(paste0("plots/map_cases_July_en", ".png"),
       map_cases_July_en, width=7.4, height=7.4, units="in")


# Korean map
# Define the replacements
replacements <- c("Chagang-do"     = "자강",
                  "Hamgyŏng-bukto" = "함북",
                  "Hamgyŏng-namdo" = "함남",
                  "Hwanghae-bukto" = "황북",
                  "Hwanghae-namdo" = "황남", 
                  "Kaesŏng"        = " ",
                  "Kangwŏn-do"     = "강원",
                  "Kumgangsan"     = " ",
                  "P'yŏngan-bukto" = "평북",
                  "P'yŏngan-namdo" = "평남",
                  "P'yŏngyang"     = "평양",
                  "Rasŏn"          = " ",
                  "Ryanggang"      = "양강",
                  "Sinŭiju"        = " ")

# modify labels in cnames data frame
cnames$id <- str_replace_all(cnames$id, replacements)

# correct label location
print(cnames)
cnames$lat[cnames$id == "평북"]   <- 40
cnames$long[cnames$id == "평북"]  <- 125.2
cnames$lat[cnames$id == "평남"]   <- 39.5
cnames$long[cnames$id == "평남"]  <- 126
cnames$lat[cnames$id == "함남"]   <- 40.25
cnames$lat[cnames$id == "황남"]   <- 38.25

cnames$lat[cnames$id == "강원"]   <- 38.7
cnames$long[cnames$id == "강원"]  <- 127.5
cnames$lat[cnames$id == "함북"]   <- 41.7
cnames$long[cnames$id == "함북"]  <- 129.5
cnames$long[cnames$id == "양강"]  <- 128.25

# create the map with province name: cases in May
map_cases_May <- map_May  + 
  geom_text(data = cnames, aes(x = long, y = lat, label = id), size = 4, color = "#505050") +
  scale_fill_gradientn(colors = brewer.pal(9, "YlOrBr"),
                       limits = c(0, max(df_month$adding_new_cases)),
                       breaks = seq(0, max(df_month$adding_new_cases), 100000),
                       labels = comma,
                       "신규 유열자 (5월)") +
  theme(legend.position = c(0.9, 0.25))

# save the map with the province name: cases in May
ggsave(paste0("plots/map_cases_May", tstamp(), ".png"),
       map_cases_May, width=7.4, height=7.4, units="in")

# create the map with province name: cases in June
map_cases_June <- map_June  + 
  geom_text(data = cnames, aes(x = long, y = lat, label = id), size = 4, color = "#505050") +
  scale_fill_gradientn(colors = brewer.pal(9, "YlOrBr"),
                       limits = c(0, max(df_month$adding_new_cases)),
                       breaks = seq(0, max(df_month$adding_new_cases), 100000),
                       labels = comma,
                       "신규 유열자 (6월)") +
  theme(legend.position = c(0.9, 0.25))

# save the map with the province name: cases in June
ggsave(paste0("plots/map_cases_June", tstamp(), ".png"),
       map_cases_June, width=7.4, height=7.4, units="in")

# create the map with province name: cases in July
map_cases_July <- map_July  + 
  geom_text(data = cnames, aes(x = long, y = lat, label = id), size = 4, color = "#505050") +
  scale_fill_gradientn(colors = brewer.pal(9, "YlOrBr"),
                       limits = c(0, max(df_month$adding_new_cases)),
                       breaks = seq(0, max(df_month$adding_new_cases), 100000),
                       labels = comma,
                       "신규 유열자 (7월)") +
  theme(legend.position = c(0.9, 0.25))

# save the map with the province name: cases in July
ggsave(paste0("plots/map_cases_July", tstamp(), ".png"),
       map_cases_July, width=7.4, height=7.4, units="in")

```



```{r}
# attack rate heat map -- used JHK's code
# added the province names
library(lubridate)
library(data.table)
library(scales)
library(ggplot2)
library(RColorBrewer)

dprk = rgdal::readOGR("inst/extdata/gadm41_PRK_shp", "gadm41_PRK_1")
dprk@data$name_kor = c("자강","함북","함남","황북","황남","개성","강원","강원","평북","평남","평양","나선","양강","평북")

dprk@data$AR = NA
nm = dprk@data$name_kor
for (n in nm){
  dprk@data[dprk@data$name_kor == n,]$AR = df_ds[df_ds$Province_Korean == n,]$attack_rate
}

dprk@data[dprk@data$name_kor  == "개성",]$AR =
  df_ds[df_ds$Province_Korean == "황북",]$attack_rate
dprk@data[dprk@data$name_kor  == "나선",]$AR =
  df_ds[df_ds$Province_Korean == "함북",]$attack_rate

dprk_df <- broom::tidy(dprk, region = "AR")
head(dprk_df)
dprk_df$id <- as.double(dprk_df$id) # attack rate

library(ggplot2)
library(RColorBrewer)

# create the map plot
map <- ggplot(data = dprk_df) +
  geom_polygon(aes(x = long, y = lat, group = group, fill = id),
               color = 'black', linewidth = 0.5) +
  coord_equal() +
  theme_map()

# add province name
shp = rgdal::readOGR("inst/extdata/gadm41_PRK_shp", "gadm41_PRK_1")
shp_df <- broom::tidy(shp, region = "NAME_1")

# create the map plot with province name
cnames <- aggregate(cbind(long, lat) ~ id, data = shp_df, FUN = mean)

library(stringr)
unique_names <- unique(cnames$id)

# English map
# define the replacements
replacements <- c("Chagang-do"     = "Jagang",
                  "Hamgyŏng-bukto" = "North Hamgyong",
                  "Hamgyŏng-namdo" = "South Hamgyong",
                  "Hwanghae-bukto" = "North Hwanghae",
                  "Hwanghae-namdo" = "South Hwanghae", 
                  "Kaesŏng"        = " ",
                  "Kangwŏn-do"     = "Gangwon",
                  "Kumgangsan"     = " ",
                  "P'yŏngan-bukto" = "North Pyongan",
                  "P'yŏngan-namdo" = "South Pyongan",
                  "P'yŏngyang"     = "Pyongyang",
                  "Rasŏn"          = " ",
                  "Ryanggang"      = "Ryanggang",
                  "Sinŭiju"        = " ")

# Modify labels in cnames data frame
cnames$id <- str_replace_all(cnames$id, replacements)

# correct label location
cnames$lat[cnames$id  == "North Pyongan"]   <- 40
cnames$long[cnames$id == "North Pyongan"]   <- 125.2
cnames$lat[cnames$id  == "South Pyongan"]   <- 39.45
cnames$long[cnames$id == "South Pyongan"]   <- 126.1
cnames$lat[cnames$id  == "South Hamgyong"]  <- 40.25
cnames$long[cnames$id == "South Hamgyong"]  <- 127.8
cnames$lat[cnames$id  == "South Hwanghae"]  <- 38.3
cnames$long[cnames$id == "South Hwanghae"]  <- 125.6

cnames$lat[cnames$id  == "Gangwon"]         <- 38.7
cnames$long[cnames$id == "Gangwon"]         <- 127.5
cnames$lat[cnames$id  == "North Hamgyong"]  <- 42
cnames$long[cnames$id == "North Hamgyong"]  <- 129.6
cnames$long[cnames$id == "Ryanggang"]       <- 128.25

# create the map plot with province name (dark green color)
map_PN_en <- map + 
  geom_text(data = cnames, aes(x = long, y = lat, label = id), size = 4, color = "#505050") +
  scale_fill_gradientn(colors = brewer.pal(9, "YlOrBr"),
                       limits = c(0, max(dprk_df$id)),
                       breaks = seq(0, max(dprk_df$id), 5),
                       "Attack rate (%)") +
  theme(legend.position = c(0.9, 0.25),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 12))

# save the plot with the province name
ggsave(paste0("plots/ar_PN_en", ".png"),
          map_PN_en, width=7.4, height=7.4, units="in")

# Korean map
# define the replacements
replacements <- c("Chagang-do"     = "자강",
                  "Hamgyŏng-bukto" = "함북",
                  "Hamgyŏng-namdo" = "함남",
                  "Hwanghae-bukto" = "황북",
                  "Hwanghae-namdo" = "황남", 
                  "Kaesŏng"        = " ",
                  "Kangwŏn-do"     = "강원",
                  "Kumgangsan"     = " ",
                  "P'yŏngan-bukto" = "평북",
                  "P'yŏngan-namdo" = "평남",
                  "P'yŏngyang"     = "평양",
                  "Rasŏn"          = " ",
                  "Ryanggang"      = "양강",
                  "Sinŭiju"        = " ")

# Modify labels in cnames data frame
cnames$id <- str_replace_all(cnames$id, replacements)

# correct label location
print(cnames)
cnames$lat[cnames$id   == "평북"]   <- 40
cnames$long[cnames$id  == "평북"]   <- 125.2
cnames$lat[cnames$id   == "평남"]   <- 39.5
cnames$long[cnames$id  == "평남"]   <- 126
cnames$lat[cnames$id   == "함남"]   <- 40.25
cnames$lat[cnames$id   == "황남"]   <- 38.25

cnames$lat[cnames$id   == "강원"]   <- 38.7
cnames$long[cnames$id  == "강원"]   <- 127.5
cnames$lat[cnames$id   == "함북"]   <- 41.7
cnames$long[cnames$id  == "함북"]   <- 129.5
cnames$long[cnames$id  == "양강"]   <- 128.25

# create the map plot with province name (dark green color)
map_PN_kr <- map + 
  geom_text(data = cnames, aes(x = long, y = lat, label = id), size = 4, color = "#505050") +
  scale_fill_gradientn(colors = brewer.pal(9, "YlOrBr"),
                       limits = c(0, max(dprk_df$id)),
                       breaks = seq(0, max(dprk_df$id), 5),
                       "발병률(%)") +
  theme(legend.position = c(0.9, 0.25),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 12))

# save the plot with the province name
ggsave(paste0("plots/ar_PN_kr",".png"),
       map_PN_kr, width=7.4, height=7.4, units="in")

```



```{r}
# estimate case-fatality ratio
library(dplyr)
library(lubridate)
library(data.table)
library(scales)
library(ggplot2)
library(RColorBrewer)

df_cfr <- df_ds
df_cfr <- df_cfr[!df_cfr$province %in% c("개성", "나선"), ]
df_cfr <- df_cfr[order(df_cfr$province), ]

# df_cfr에서 필요한 컬럼만 선택
df_cfr <- df_cfr %>% select(province, Province, cumulative_recovered, cumulative_deaths)

# 총합 행 추가
total_row <- df_cfr %>%
  summarise(province = "총합",
            Province = "Sum",
            cumulative_recovered = sum(cumulative_recovered),
            cumulative_deaths = sum(cumulative_deaths))

df_cfr <- rbind(df_cfr, total_row)

# case-fatality ratio 계산
df_cfr <- df_cfr %>%
  mutate(recovered_deaths = cumulative_recovered + cumulative_deaths) %>%
  mutate(case_fatality_ratio = cumulative_deaths / recovered_deaths)

# case_fatality_ratio 형식 변경
df_cfr$case_fatality_ratio <- df_cfr$case_fatality_ratio * 100

# case_fatality_ratio 컬럼 값 숫자별로 다른 자릿수로 반올림
cfr_table <- df_cfr
cfr_table$case_fatality_ratio <- lapply(cfr_table$case_fatality_ratio, function(x) {
  round(as.numeric(x), digits = max(0, 2 - floor(log10(abs(as.numeric(x))))))
})

cfr_table$case_fatality_ratio <- paste0(cfr_table$case_fatality_ratio, "%")

cfr_table$cumulative_recovered <- sapply(cfr_table$cumulative_recovered, format, big.mark = ",")
cfr_table$cumulative_deaths <- sapply(cfr_table$cumulative_deaths, format, big.mark = ",")
cfr_table$recovered_deaths <- sapply(cfr_table$recovered_deaths, format, big.mark = ",")

cfr_table_en <- cfr_table %>% select(Province, cumulative_recovered, cumulative_deaths,   
                                     recovered_deaths, case_fatality_ratio) 
cfr_table_kr <- cfr_table %>% select(province, cumulative_recovered, cumulative_deaths,   
                                     recovered_deaths, case_fatality_ratio)

cfr_table_en <- cfr_table_en[order(cfr_table_en$Province == "Sum", cfr_table_en$Province), ]

write.csv(cfr_table_en, file = "outputs/cfr_table_en.csv", row.names = FALSE)
write.csv(cfr_table_kr, file = "outputs/cfr_table_kr.csv", row.names = FALSE)

  #------------------------------------------------------------------------

# create combined table - attack rate + case fatality ratio

# Rason and Kaesong are calculated by merging North Hamgyeong and North Hwanghae
cfr_table_en <- cfr_table %>% select(Province, case_fatality_ratio) 

# merge the two tables
table_AT_CFR <- left_join(summary_table_en, cfr_table_en, by = "Province")

write.csv(table_AT_CFR, file = "outputs/table_AT_CFR.csv", row.names = FALSE)

  #------------------------------------------------------------------------

# 지도 그리기
dprk = rgdal::readOGR("inst/extdata/gadm41_PRK_shp", "gadm41_PRK_1")
dprk@data$name_kor = c("자강","함북","함남","황북","황남","개성","강원","강원","평북","평남","평양","나선","양강","평북")

dprk@data$deaths  = NA
dprk@data$cfr  = NA

nm = dprk@data$name_kor

df_cfr <- df_cfr[df_cfr$province != "총합", ]

for (n in nm){
  dprk@data[dprk@data$name_kor == n,]$deaths = df_cfr[df_cfr$province == n,]$cumulative_deaths}

for (n in nm){
  dprk@data[dprk@data$name_kor == n,]$cfr = df_cfr[df_cfr$province == n,]$case_fatality_ratio}

# tidy the data
dprk_df_deaths <- broom::tidy(dprk, region = "deaths")
dprk_df_deaths$id <- as.double(dprk_df_deaths$id)

dprk_df_cfr <- broom::tidy(dprk, region = "cfr")
dprk_df_cfr$id <- as.double(dprk_df_cfr$id)

# create the map plot for deaths
map_deaths <- ggplot(data = dprk_df_deaths) +
  geom_polygon(aes(x = long, y = lat, group = group, fill = id),
               color = 'black', linewidth = 0.5) +
  coord_equal() +
  theme_map() +
  theme(legend.title = element_text(size = 12),
        legend.text = element_text(size = 12))

# create the map plot for cfr
map_cfr <- ggplot(data = dprk_df_cfr) +
  geom_polygon(aes(x = long, y = lat, group = group, fill = id),
               color = 'black', linewidth = 0.5) +
  coord_equal() +
  theme_map() +
  theme(legend.title = element_text(size = 12),
        legend.text = element_text(size = 12))

# add province name
shp = rgdal::readOGR("inst/extdata/gadm41_PRK_shp", "gadm41_PRK_1")
shp_df <- broom::tidy(shp, region = "NAME_1")

# create the map plot with province name
cnames <- aggregate(cbind(long, lat) ~ id, data = shp_df, FUN = mean)

library(stringr)
unique_names <- unique(cnames$id)

# English map
# define the replacements
replacements <- c("Chagang-do"     = "Jagang",
                  "Hamgyŏng-bukto" = "North Hamgyong",
                  "Hamgyŏng-namdo" = "South Hamgyong",
                  "Hwanghae-bukto" = "North Hwanghae",
                  "Hwanghae-namdo" = "South Hwanghae", 
                  "Kaesŏng"        = " ",
                  "Kangwŏn-do"     = "Gangwon",
                  "Kumgangsan"     = " ",
                  "P'yŏngan-bukto" = "North Pyongan",
                  "P'yŏngan-namdo" = "South Pyongan",
                  "P'yŏngyang"     = "Pyongyang",
                  "Rasŏn"          = " ",
                  "Ryanggang"      = "Ryanggang",
                  "Sinŭiju"        = " ")

# Modify labels in cnames data frame
cnames$id <- str_replace_all(cnames$id, replacements)

# correct label location
cnames$lat[cnames$id  == "North Pyongan"]   <- 40
cnames$long[cnames$id == "North Pyongan"]   <- 125.2
cnames$lat[cnames$id  == "South Pyongan"]   <- 39.45
cnames$long[cnames$id == "South Pyongan"]   <- 126.1
cnames$lat[cnames$id  == "South Hamgyong"]  <- 40.25
cnames$long[cnames$id == "South Hamgyong"]  <- 127.8
cnames$lat[cnames$id  == "South Hwanghae"]  <- 38.3
cnames$long[cnames$id == "South Hwanghae"]  <- 125.6

cnames$lat[cnames$id  == "Gangwon"]         <- 38.7
cnames$long[cnames$id == "Gangwon"]         <- 127.5
cnames$lat[cnames$id  == "North Hamgyong"]  <- 42
cnames$long[cnames$id == "North Hamgyong"]  <- 129.6
cnames$long[cnames$id == "Ryanggang"]       <- 128.25

# create the map with province name: cfr
map_cfr_number_en <- map_cfr  + 
  geom_text(data = cnames, aes(x = long, y = lat, label = id), size = 4, color = "#505050") +
  scale_fill_gradientn(colors = brewer.pal(9, "YlOrBr"),
                       limits = c(0, max(df_cfr$case_fatality_ratio) + 0.001),
                       breaks = seq(0, max(df_cfr$case_fatality_ratio), 0.002),
                       labels = comma,
                       "Case-fatality ratio (%)") +
  theme(legend.position = c(0.85, 0.25))

# save the map with the province name: cfr
ggsave(paste0("plots/map_cfr_number_en",".png"),
       map_cfr_number_en, width=7.4, height=7.4, units="in")

# Korean map
# define the replacements
replacements <- c("Chagang-do"     = "자강",
                  "Hamgyŏng-bukto" = "함북",
                  "Hamgyŏng-namdo" = "함남",
                  "Hwanghae-bukto" = "황북",
                  "Hwanghae-namdo" = "황남", 
                  "Kaesŏng"        = " ",
                  "Kangwŏn-do"     = "강원",
                  "Kumgangsan"     = " ",
                  "P'yŏngan-bukto" = "평북",
                  "P'yŏngan-namdo" = "평남",
                  "P'yŏngyang"     = "평양",
                  "Rasŏn"          = " ",
                  "Ryanggang"      = "양강",
                  "Sinŭiju"        = " ")

# modify labels in cnames data frame
cnames$id <- str_replace_all(cnames$id, replacements)

# correct label location
print(cnames)
cnames$lat[cnames$id == "평북"]   <- 40
cnames$long[cnames$id == "평북"]  <- 125.2
cnames$lat[cnames$id == "평남"]   <- 39.5
cnames$long[cnames$id == "평남"]  <- 126
cnames$lat[cnames$id == "함남"]   <- 40.25
cnames$lat[cnames$id == "황남"]   <- 38.25

cnames$lat[cnames$id == "강원"]   <- 38.7
cnames$long[cnames$id == "강원"]  <- 127.5
cnames$lat[cnames$id == "함북"]   <- 41.7
cnames$long[cnames$id == "함북"]  <- 129.5
cnames$long[cnames$id == "양강"]  <- 128.25

# create the map with province name: deaths
map_deaths_number  <- map_deaths  + 
  geom_text(data = cnames, aes(x = long, y = lat, label = id), size = 4, color = "#505050") +
  scale_fill_gradientn(colors = brewer.pal(9, "YlOrBr"),
                       limits = c(0, max(df_cfr$cumulative_deaths)),
                       breaks = seq(0, max(df_cfr$cumulative_deaths), 3),
                       "사망자 수") +
  theme(legend.position = c(0.9, 0.25))

# save the map with the province name: deaths
ggsave(paste0("plots/map_deaths_number",".png"),
       map_deaths_number, width=7.4, height=7.4, units="in")

# create the map with province name: cfr
map_cfr_number <- map_cfr  + 
  geom_text(data = cnames, aes(x = long, y = lat, label = id), size = 4, color = "#505050") +
  scale_fill_gradientn(colors = brewer.pal(9, "YlOrBr"),
                       limits = c(0, max(df_cfr$case_fatality_ratio) + 0.001),
                       breaks = seq(0, max(df_cfr$case_fatality_ratio), 0.002),
                       labels = comma,
                       "치명률 (%)") +
  theme(legend.position = c(0.9, 0.25))

# save the map with the province name: cfr
ggsave(paste0("plots/map_cfr_number",".png"),
       map_cfr_number, width=7.4, height=7.4, units="in")

```



```{r}
# Comparing incidence rate with the neighboring countries
library(dplyr)
library(tidyr)
library(lubridate)
library(tidyverse)
library(ggplot2)
library(readxl)
library(data.table)

## North Korea data (노동신문)
# import data
summary_dates_labor <- read_excel("inst/extdata/(2022-0811)_코로나19_노동신문_보도_현황표_전체_일일유열자 2.xlsx")
names(summary_dates_labor) <- c("기준일", "신규 유열자(노동신문)", "완쾌자(노동신문)", "사망자(노동신문)")

# estimate new cases per million
# New Cases per Million = (New Cases / Population) * 1,000,000
summary_dates_labor <- summary_dates_labor %>% 
  mutate ("new_cases_per_million" = (`신규 유열자(노동신문)` / 25697258) * 1000000)
# estimated number of population in 2022; 25,697,258
# reference: KOSIS (https://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_IZGA01_002&vw_cd=MT_BUKHAN&list_id=101_101BUKHANB12&scrId=&seqNo=&lang_mode=ko&obj_var_id=&itm_id=&conn_path=MT_BUKHAN&path=%252FstatisticsList%252FstatisticsListIndex.do)

## World data
# import data
data_other_countries <- read_csv("data/owid-covid-data_nighbouring-countries.csv")

# data cleaning
df_dates <- data_other_countries %>% # 2020-01-03 / 2023-07-05
  group_by(location) %>%
  summarize(initial_record_date   = min(date[!is.na(new_cases_per_million)]),
            final_record_date     = max(date[!is.na(new_cases_per_million)]))

location_na <- data_other_countries %>%
  filter(date == "2021-01-03" & is.na(new_cases_per_million)) %>%
  select(location)

data_other_countries <- data_other_countries %>%
  filter(!location %in% location_na$location,
         !(location %in% c("Macao", "Northern Cyprus")))

df_do <- data_other_countries %>%
  filter(date <= as.Date("2023-06-30"))

# check NAs. replace NAs to 0
# na_rows_c <- df_do[is.na(df_do$new_cases_per_million), ]
# na_rows_d <- df_do[is.na(df_do$new_deaths_per_million), ]
df_do <- df_do %>%
  mutate_at(vars(new_deaths_per_million, new_cases_per_million), ~replace_na(., 0))
df_do$iso_code[df_do$iso_code == "OWID_KOS"] <- "XK"

  #-----------------------------------------------------------------------
## merge with NK 노동신문 data
# Filter rows in df_do where location is "North Korea"
df_do_filtered <- df_do %>%
  filter(location == "North Korea")

# Perform a left join with summary_dates_labor on matching dates
df_nk <- df_do_filtered %>%
  left_join(summary_dates_labor, by = c("date" = "기준일"))

# Update the 'new_cases_per_million' column in df_do with values from summary_dates_labor
df_nk <- df_nk %>%
  mutate(new_cases_per_million = ifelse(!is.na(new_cases_per_million.y), new_cases_per_million.y, new_cases_per_million.x)) %>%
  select(-c(new_cases_per_million.x, new_cases_per_million.y))

# Combine the updated result back with the original df_do
df_do <- bind_rows(
  df_do %>%
    filter(location != "North Korea"), # Exclude North Korea rows
  df_nk)

#-----------------------------------------------------------------------
# generate the table for the Covid cases and deaths for other countries

# generate the table
df_do_year <- df_do %>%
  mutate(year = year(date)) %>%
  group_by(iso_code, continent, location, year) %>%
  summarise(new_cases_per_million = sum(new_cases_per_million),
           new_deaths_per_million = sum(new_deaths_per_million),
            .groups = 'drop')

# new cases per million by year
df_new_cases <- df_do_year %>%
  select(-new_deaths_per_million) %>%
  pivot_wider(names_from = year,
              values_from = new_cases_per_million) %>%
  rename_with(~paste0(., "_new_cases_per_million"), .cols = -c(1:3))

# new deaths per million by year
df_new_deaths <- df_do_year %>%
  select(-new_cases_per_million) %>%
  pivot_wider(names_from = year,
              values_from = new_deaths_per_million) %>%
  rename_with(~paste0(., "_new_deaths_per_million"), .cols = -c(1:3))

df_combined <- left_join(df_new_cases, df_new_deaths, by = c("iso_code", "continent", "location"))

# OWID
df_OWID <- df_combined[grep("^OWID", df_combined$iso_code), ]
df_countries <- df_combined[!grepl("^OWID", df_combined$iso_code), ]

# save csv file
write.csv(df_countries, "outputs/df_countries.csv", row.names = FALSE)

#-----------------------------------------------------------------------
# generate the table for the Covid cases and deaths for other countries
# during the period when NK data is available

# Select data from 2022-05-12 to 2022-08-09
# generate the table
df_do_year_NKperiod <- df_do %>%
   filter(date >= as.Date("2022-05-12") & date <= as.Date("2022-08-09")) %>%
  mutate(year = year(date)) %>%
  group_by(iso_code, continent, location, year) %>%
  summarise(new_cases_per_million = sum(new_cases_per_million),
           new_deaths_per_million = sum(new_deaths_per_million),
            .groups = 'drop')

# new cases per million by year
df_new_cases_NKperiod <- df_do_year_NKperiod %>%
  select(-new_deaths_per_million) %>%
  pivot_wider(names_from = year,
              values_from = new_cases_per_million) %>%
  rename_with(~paste0(., "_new_cases_per_million"), .cols = -c(1:3))

# new deaths per million by year
df_new_deaths_NKperiod <- df_do_year_NKperiod %>%
  select(-new_cases_per_million) %>%
  pivot_wider(names_from = year,
              values_from = new_deaths_per_million) %>%
  rename_with(~paste0(., "_new_deaths_per_million"), .cols = -c(1:3))

df_combined_NKperiod <- left_join(df_new_cases_NKperiod, df_new_deaths_NKperiod, 
                         by = c("iso_code", "continent", "location"))

# OWID
df_OWID_NKperiod <- df_combined_NKperiod[grep("^OWID", df_combined_NKperiod$iso_code), ]
df_countries_NKperiod <- df_combined_NKperiod[!grepl("^OWID", df_combined_NKperiod$iso_code), ]

# save csv file
write.csv(df_countries_NKperiod, "outputs/df_countries_NKperiod.csv", row.names = FALSE)

#-----------------------------------------------------------------------
# generate box plot

# global
ggplot(data = df_countries, aes(x = "", y = `2022_new_cases_per_million`)) +
  geom_boxplot() +
  scale_y_continuous(labels = function(x) format(x, scientific = FALSE)) +
  theme_bw() +
  labs(title = "2022 New Cases per Million",
       y = "New Cases per Million",
       x = "Global")

# regional
ggplot(data = df_countries, aes(x = continent, y = `2022_new_cases_per_million`)) +
  geom_boxplot() +
  scale_y_continuous(labels = function(x) format(x, scientific = FALSE)) +
  theme_bw() +
  labs(title = "2022 New Cases per Million by Continent",
       y = "New Cases per Million",
       x = "Continent")

ggplot(data = df_countries, aes(x = continent, y = `2022_new_deaths_per_million`)) +
  geom_boxplot() +
  scale_y_continuous(labels = function(x) format(x, scientific = FALSE)) +
  theme_bw() +
  labs(title = "2022 New Deaths per Million by Continent",
       y = "New Deaths per Million",
       x = "Continent")

# 여타 국가값 표
df_selected <- df_countries[df_countries$location %in% c("North Korea", "South Korea", "Russia", "China", "Mongolia", "Vietnam", "Cuba"), ]

ggplot(data = df_countries, aes(x = "", y = `2022_new_cases_per_million`)) +
  geom_boxplot() +
  geom_point(data = df_selected, aes(x = "", y = `2022_new_cases_per_million`, fill = location), color = "white", shape = 21, size = 1.5) +
  geom_text(data = df_selected, aes(x = "", y = `2022_new_cases_per_million`, label = location, color = location),
            vjust = 0.2, size = 3.5, nudge_x = ifelse(df_selected$location == "South Korea", 0.12, ifelse(df_selected$location %in% c("Mongolia", "China"), -0.08, 0.08)), nudge_y = -100) +
  scale_fill_manual(values = c("North Korea" = "orange", "South Korea" = "darkblue", "Russia" = "darkgreen", "China" = "red", "Mongolia" = "skyblue", "Vietnam" = "purple", "Cuba" = "brown")) +
  scale_color_manual(values = c("North Korea" = "orange", "South Korea" = "darkblue", "Russia" = "darkgreen", "China" = "red", "Mongolia" = "skyblue", "Vietnam" = "purple", "Cuba" = "brown")) +
  scale_y_continuous(labels = function(x) format(x, scientific = FALSE)) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(title = "2022 New Cases per Million",
       y = "New Cases per Million",
       x = "Global")

ggplot(data = df_countries, aes(x = "", y = `2022_new_deaths_per_million`)) +
  geom_boxplot() +
  geom_point(data = df_selected, aes(x = "", y = `2022_new_deaths_per_million`, fill = location), color = "white", shape = 21, size = 1) +
  geom_text(data = df_selected, aes(x = "", y = `2022_new_deaths_per_million`, label = location, color = location),
            vjust = ifelse(df_selected$location %in% c("Mongolia"), -1, 0), size = 3.5, nudge_x = ifelse(df_selected$location == "South Korea", 0.1, ifelse(df_selected$location %in% c("Vietnam", "Cuba"), 0.06, -0.06)), nudge_y = 0) +
  scale_fill_manual(values = c("South Korea" = "darkblue", "Russia" = "darkgreen", "China" = "red", "Mongolia" = "skyblue", "Vietnam" = "purple", "Cuba" = "brown")) +
  scale_color_manual(values = c("South Korea" = "darkblue", "Russia" = "darkgreen", "China" = "red", "Mongolia" = "skyblue", "Vietnam" = "purple", "Cuba" = "brown")) +
  scale_y_continuous(labels = function(x) format(x, scientific = FALSE)) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(title = "2022 New Deaths per Million",
       y = "New Deaths per Million",
       x = "Global")

#-----------------------------------------------------------------------
# generate box plot for the NK data period

df_selected_NKperiod <- df_countries_NKperiod[df_countries_NKperiod$location %in% c("North Korea", "South Korea", "Russia", "China", "Mongolia"), ]

ggplot(data = df_countries_NKperiod, aes(x = "", y = `2022_new_cases_per_million`)) +
  geom_boxplot() +
  geom_point(data = df_selected_NKperiod, aes(x = "", y = `2022_new_cases_per_million`, fill = location), color = "white", shape = 21, size = 1.5) +
  geom_text(data = df_selected_NKperiod, aes(x = "", y = `2022_new_cases_per_million`, label = location, color = location),
            vjust = 0.8, size = 3.5, nudge_x = ifelse(df_selected_NKperiod$location == "Mongolia", 0.08, ifelse(df_selected_NKperiod$location %in% c("South Korea", "China"), -0.08, 0.08)), nudge_y = -100) +
  scale_fill_manual(values = c("South Korea" = "darkblue", "Russia" = "darkgreen", "China" = "red", "Mongolia" = "skyblue","North Korea" = "orange")) +
  scale_color_manual(values = c("South Korea" = "darkblue", "Russia" = "darkgreen", "China" = "red", "Mongolia" = "skyblue","North Korea" = "orange")) +
  scale_y_continuous(labels = function(x) format(x, scientific = FALSE)) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(title = "New Cases per Million (2022-05-12 - 2022-08-09)",
       y = "New Cases per Million",
       x = "Global")

#-----------------------------------------------------------------------
# generate table

# select countries - South Korea, Russia, China, Mongolia, Vietnam, Cuba
countries <- c("South Korea", "Russia", "China", "Mongolia", "Vietnam", "Cuba")
data_other <- subset(df_combined, location %in% countries)

# to round decimal places to the third digit
data_other <- data_other %>%
  mutate_at(vars(-c(iso_code, continent, location)), ~ round(., digits = 2))

# save the file
write.csv(data_other, "outputs/table_new_cases_deaths_per_million_in_other_countries.csv", row.names = FALSE)

# hospitalised/icu patients per million
df_do_hos <- df_do %>%
  mutate(year = year(date)) %>%
  group_by(location, year) %>%
  summarise(hosp_patients_per_million = mean(hosp_patients_per_million, na.rm = TRUE),
            icu_patients_per_million = mean(icu_patients_per_million, na.rm = TRUE),
            .groups = 'drop') %>%
  filter(location == "South Korea")

# to round decimal places to the third digit
df_do_hos <- df_do_hos %>%
  mutate_at(vars(-location), ~ round(., digits = 2))

# save the file2
write.csv(df_do_hos, "outputs/table_hosp_icu_patients_per_million.csv", row.names = FALSE)

```

# end.
