---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---


### Downlowd the global dataset 
Global confirmed cases, recovereds, and deaths were downloaded from:
https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series
```{r}
library(data.table)
# Hopkins data set
confirmed = fread("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")

deaths = fread("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")

recovered = fread("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv")

# Our World In Data data set
owid_data = fread("https://raw.githubusercontent.com/owid/covid-19-data/37c02e9cc2501d8bd1891215b16b93ca202d187c/public/data/owid-covid-data.csv")
names(owid_data)
library(countrycode)
```

```{r}
dim(confirmed)
confirmed[1:10,1:10]
confirmed[1:10,1137:1147]
confirmed[280:289,1137:1147]
cntries = confirmed[[2]]
plot(as.Date(names(confirmed)[5:1000], format="%m/%d/%y"), confirmed[`Country/Region` =="Korea, South", 5:1000], type='l')
```

