// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// reulermultinom
NumericVector reulermultinom(double size, NumericVector rate, double dt);
RcppExport SEXP _COVID19NorthKorea_reulermultinom(SEXP sizeSEXP, SEXP rateSEXP, SEXP dtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    rcpp_result_gen = Rcpp::wrap(reulermultinom(size, rate, dt));
    return rcpp_result_gen;
END_RCPP
}
// sepiar_stoch
List sepiar_stoch(List params);
RcppExport SEXP _COVID19NorthKorea_sepiar_stoch(SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(sepiar_stoch(params));
    return rcpp_result_gen;
END_RCPP
}
// sepiar_erlang_stoch
List sepiar_erlang_stoch(List params);
RcppExport SEXP _COVID19NorthKorea_sepiar_erlang_stoch(SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(sepiar_erlang_stoch(params));
    return rcpp_result_gen;
END_RCPP
}
// sepiar_erlang_euler
List sepiar_erlang_euler(List params);
RcppExport SEXP _COVID19NorthKorea_sepiar_erlang_euler(SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(sepiar_erlang_euler(params));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_COVID19NorthKorea_reulermultinom", (DL_FUNC) &_COVID19NorthKorea_reulermultinom, 3},
    {"_COVID19NorthKorea_sepiar_stoch", (DL_FUNC) &_COVID19NorthKorea_sepiar_stoch, 1},
    {"_COVID19NorthKorea_sepiar_erlang_stoch", (DL_FUNC) &_COVID19NorthKorea_sepiar_erlang_stoch, 1},
    {"_COVID19NorthKorea_sepiar_erlang_euler", (DL_FUNC) &_COVID19NorthKorea_sepiar_erlang_euler, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_COVID19NorthKorea(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
