# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

reulermultinom <- function(size, rate, dt) {
    .Call(`_COVID19NorthKorea_reulermultinom`, size, rate, dt)
}

seapird_euler <- function(params) {
    .Call(`_COVID19NorthKorea_seapird_euler`, params)
}

seapird_tauleap <- function(params) {
    .Call(`_COVID19NorthKorea_seapird_tauleap`, params)
}

sepiar_stoch <- function(params) {
    .Call(`_COVID19NorthKorea_sepiar_stoch`, params)
}

sepiar_erlang_stoch <- function(params) {
    .Call(`_COVID19NorthKorea_sepiar_erlang_stoch`, params)
}

sepiar_erlang_euler <- function(params) {
    .Call(`_COVID19NorthKorea_sepiar_erlang_euler`, params)
}

